language: cpp
dist: trusty

# Reducing the depth when cloning using git
# https://docs.travis-ci.com/user/customizing-the-build/#git-clone-depth
git:
  depth: 3

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

matrix:
  fast_finish: true
  exclude:
    - os: osx
      compiler: gcc

